[package]
name = "code_exec"
version = "0.2.0"
edition = "2024"
authors = ["Andrewkoro105"]
license = "MIT"
repository = "https://github.com/Andrewkoro105/code_exec"
description = "A library that provides a universal API for working with various code execution systems, hiding their implementation behind a layer of traits."
keywords = ["compiler", "interop", "polyglot", "traits", "podman"]
categories = ["rust-patterns", "compilers", "config", "virtualization", "asynchronous"]

[dependencies]
serde_json = "1.0.149"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
rt-format = "0.3.1"
serde = {version = "1.0.228", features = ["derive"]}
tokio = { version = "1.53.1", features = ["fs", "time", "macros", "rt", "process", "rt-multi-thread", "io-util"] }
reqwest = { version = "0.13.5", features = ["stream", "json", "socks"]}
futures-util = "0.3"
tokio-util = { version = "0.7.19", features = ["io"] }
async-compression = { version = "0.4.48", features = ["tokio", "gzip"] }
tokio-tar = "0.3.1"
sugar = "0.2.0"
#pty-process = { version = "0.5.3", features = ["async"] }

[features]
default = []
from_sys = []
podman = ["from_sys"]

